### ISSUE TITLE
Selecting a scaling other than 100% or 200% scales at 200% (Arch)

### ISSUE THREAD

**Issue by caleb** [puxplaying/mutter-x11-scaling#5]
Hi,

I'm on Arch Linux and I know this is for Manjaro, but I thought you might have some insight into this.

I used this package on the previous version of Gnome (3.34) and it worked perfectly, but since the upgrade to 3.36 selecting a scaling other than 100 or 200 just scales everything really large (which looks like 200%) and my screen pans with the mouse.

I installed the package like I usually do: `makepkg -srci`, enabled the setting to enable fractional scaling as your README says and rebooted the machine.

My Arch up-to-date running Gnome 3.36.2, any ideas?

**Comment by puxplaying** [comment]
Hi @caleb , thanks for the report. 
I have just pushed a updated scaling patch from upstream, could you please check if the new build still has the same issue for you?

Theoretically this `mutter` build should work equal on Arch as i use arch's PKGBUILD and there are no Manjaro specific changes.

**Comment by caleb** [comment]
That didn't fix it unfortunately.

It still selects "200%" when I try to apply "125%". Strangely enough, if I pick 150% or 175% the screen goes black and I have to wait for it to timeout to revert my settings back.

Is there a place upstream that is better to ask this?

I'm on an Nvidia 2080ti with the latest proprietary driver on Arch.

**Comment by puxplaying** [comment]
I think you could ask Marco Trevisan on their [Gitlab](https://salsa.debian.org/gnome-team/mutter/-/blob/ubuntu/master/debian/patches/x11-Add-support-for-fractional-scaling-using-Randr.patch) page if this are known issues, however as long as this problem only occurs with my port and not on Ubuntu i think it's gonna be difficult.

**Comment by caleb** [comment]
It looks like this is a known bug:

https://bugs.launchpad.net/ubuntu/+source/gnome-control-center/+bug/1870736

I tried the Ubuntu installer by the way and it works even less than this patch in Arch... selecting fractional scaling displays a glitchy rainbow and the screen is unusable.

Thanks for your help, this card is too new for Linux, the OSS drivers don’t work with it either.

**Comment by caleb** [comment]
By the way, I tried this package again yesterday and it works correctly. I don't know if something got fixed upstream or if deleting the git repo and re-cloning it helped, but it works now!

Thanks! This should be included in the upstream mutter IMHO. High DPI screens are pretty popular nowadays.

**Comment by puxplaying** [comment]
I'm glad it works for you again, hope you can enjoy it now! Upstream seems to prioritize fractional scaling on Wayland as they offer it by default. AFAIK Ubuntu is still working to upstream this patch for Xorg.
